CC = g++
FILES = visualiser.cpp Declares.h
OUT_EXE = visualiser.exe
FLAGS = -O3 
LINKS = -lGL -lGLU -lglut
visualiser.exe : visualiser.cpp Declares.h
	${CC} $(Files) -o $(OUT_EXE) $(FLAGS) $(LINKS)